# Generated by Django 3.2.2 on 2021-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210512_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combobox',
            name='content_1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='combobox',
            name='content_2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='combobox',
            name='content_3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='combobox',
            name='content_4',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='combobox',
            name='content_5',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='combobox',
            name='content_6',
            field=models.ImageField(upload_to=''),
        ),
    ]
