# Generated by Django 3.2.2 on 2021-05-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210512_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('E_mail', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=16)),
                ('Mobile_No', models.IntegerField(max_length=10)),
            ],
        ),
    ]
