# Generated by Django 3.2.2 on 2021-05-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile_No',
            field=models.CharField(max_length=10),
        ),
    ]
