# Generated by Django 3.2.2 on 2021-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210516_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(upload_to='')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Price', models.CharField(max_length=10)),
            ],
        ),
    ]
