# Generated by Django 3.2.2 on 2021-05-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
